
trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  ProjectName: '**/*.csproj'

steps:

- template: templates/Build.yml
  parameters:
    buildConfiguration: 'Release'
- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'HelloWorldApp-ServiceConnection'
    appType: 'webApp'
    WebAppName: 'hwa-dev'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'HelloWorldApp-ServiceConnection'
    appType: 'webApp'
    WebAppName: 'hwa-qa'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
