# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  ProjectName: '**/*.csproj'

steps:
# - task: DotNetCoreCLI@2
#   displayName: Restore
#   inputs:
#     command: 'restore'
#     projects: '$(ProjectName)'
#     feedsToUse: 'select'

# - task: DotNetCoreCLI@2
#   displayName: Build
#   inputs:
#     command: 'build'
#     projects: '$(ProjectName)'
#     arguments: '--configuration $(buildConfiguration)'
# - task: DotNetCoreCLI@2
#   displayName: Publish  
#   inputs:
#     command: 'publish'
#     publishWebProjects: true
#     arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'

# - template: templates/Build.yml
#   parameters:
#     buildConfiguration: 'Debug'

- template: templates/Build.yml
  parameters:
    buildConfiguration: 'Release'

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests - $(buildConfiguration)'
  inputs:
    command: 'test'
    arguments: '--no-build --configuration $(buildConfiguration)'
    publishTestResults: true
    projects: '**/*Tests.csproj'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
