
trigger:
- master

stages:
- stage: "BuildStage"
  jobs:
  - job: "BuildJob"
    pool:
      vmImage: ubuntu-latest

    variables:
      buildConfiguration: 'Release'
      ProjectName: '**/*.csproj'

    steps:

    - template: templates/Build.yml
      parameters:
        buildConfiguration: 'Release'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: "DeployToDev"
  dependsOn: "BuildStage" 
  jobs:
  - job: 
    pool:
      vmImage: ubuntu-latest
    steps:
      - download: current
        artifact: drop
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'HelloWorldApp-ServiceConnection'
          appType: 'webApp'
          WebAppName: 'hwa-dev'
          packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

- stage: "DeployToQA"
  dependsOn: "DeployToDev" 
  jobs:
  - job: 
    pool:
      vmImage: ubuntu-latest
    steps:
      - download: current
        artifact: drop
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'HelloWorldApp-ServiceConnection'
          appType: 'webApp'
          WebAppName: 'hwa-qa'
          packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
          
- stage: "DeployToProd"
  dependsOn: "DeployToQA" 
  jobs:
  - job: 
    pool:
      vmImage: ubuntu-latest
    steps:
      - download: current
        artifact: drop
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'HelloWorldApp-ServiceConnection'
          appType: 'webApp'
          WebAppName: 'hwa-prod'
          deployToSlotOrASE: true
          ResourceGroupName: 'dskrishnu-rg'
          SlotName: 'staging'
          packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
      - task: AzureAppServiceManage@0
        inputs:
          azureSubscription: 'HelloWorldApp-ServiceConnection'
          Action: 'Swap Slots'
          WebAppName: 'hwa-prod'
          ResourceGroupName: 'dskrishnu-rg'
          SourceSlot: 'staging'

