
trigger:
- none
##- master
##- development

stages:
- stage: "BuildStage"
  jobs:
  - job: "BuildJob"
    pool:
      vmImage: windows-latest

    variables:
      group: 
      buildConfiguration: 'Release'
      ProjectName: '**/*.csproj'

    steps:

    - template: templates/Build.yml
      parameters:
        buildConfiguration: 'Release'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: "DeployToDev"
  dependsOn: "BuildStage" 
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/development')
  jobs:
  - deployment: 
    environment: Development
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: drop
            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 'HelloWorldApp-ServiceConnection'
                appType: 'webApp'
                WebAppName: 'hwa-dev'
                packageForLinux: '$(pipeline.workspace)/**/*.zip'

