
trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureKeyVault@2
  displayName: Fetching Secret from Azure Keyvault
  inputs:
    azureSubscription: 'HelloWorldApp-ServiceConnection'
    KeyVaultName: 'MyDevopsDemo-KV'
    SecretsFilter: '*'
    RunAsPreJob: false
 
- task: file-creator@6
  displayName: Creating file with Secret Value
  inputs:
    filepath: '$(Build.ArtifactStagingDirectory)/kv.txt'
    filecontent: 'Value of secret : $(Secret1)'

- task: PublishBuildArtifacts@1
  displayName: Publishing File 
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'