
trigger:
- none

pool:
  vmImage: windows-latest

steps:

- task: TerraformInstaller@0
  displayName: Installing Terraform  
  inputs:
    terraformVersion: 'latest'
 
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'HelloWorldApp.Web/Terraform-templates'
    backendServiceArm: 'HelloWorldApp-ServiceConnection'
    backendAzureRmResourceGroupName: 'dskrishnu-rg'
    backendAzureRmStorageAccountName: 'mydevops'
    backendAzureRmContainerName: 'terraform'
    backendAzureRmKey: 'tf/terraform.tfstate'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'HelloWorldApp.Web/Terraform-templates'
    environmentServiceNameAzureRM: 'HelloWorldApp-ServiceConnection'